### PR TITLE
refactor(database): use compress() and decompress() helpers

### PR DESCRIPTION
**Pull request by jbrockopp**
This adds some helper functions for compressing and decompressing values in the `go-vela/types/database` package:

* [compress()](https://github.com/go-vela/types/blob/refactor/database/compression/database/compression.go#L13-L46)
* [decompress()](https://github.com/go-vela/types/blob/refactor/database/compression/database/compression.go#L48-L73)

Also updated the types performing compression to call these helper functions:

* [log.Compress()](https://github.com/go-vela/types/blob/refactor/database/compression/database/log.go#L38-L53)
* [log.Decompress()](https://github.com/go-vela/types/blob/refactor/database/compression/database/log.go#L55-L70)
* [pipeline.Compress()](https://github.com/go-vela/types/blob/refactor/database/compression/database/pipeline.go#L56-L71)
* [pipeline.Decompress()](https://github.com/go-vela/types/blob/refactor/database/compression/database/pipeline.go#L73-L88)

This benefits us by reducing the non-test LOC for compression and removing duplicate code in multiple files.

This also ensures all compression functions follow the same code path making future changes easier.

### CODE REVIEW

**Review by ecrupper — APPROVED** [review]
LGTM.

I like it, and it follows the pattern for how we handle encryption

**Review by wass3r — COMMENTED** [review]
looks good, but wondering if we should follow suit with what has been promoted here: https://github.com/go-vela/server/pull/627#discussion_r854275664 and wrap the table tests in `t.Run`?

**Review by kneal — APPROVED** [review]
LGTM 🐬 

_But also +1 to what David said_

**Comment by jbrockopp** [comment]
@wass3r @kneal done 👍

**Review by kneal — APPROVED** [review]
LGTM 🐬

**Review by wass3r — APPROVED** [review]

**Review by cognifloyd — APPROVED** [review]

**Pull request merged**
